USE ROLE ACCOUNTADMIN; 
USE DATABASE DOT_FLIGHTS; 
USE SCHEMA RAW; 
USE WAREHOUSE DOT_FLIGHTS_WH; 

CREATE OR REPLACE TABLE RAW_FLIGHTS (

-- All 100 DOT columns as VARCHAR. Raw layer keeps the source shape exactly. 

    "Year"                              VARCHAR,
    "Quarter"                           VARCHAR,
    "Month"                             VARCHAR,
    "DayofMonth"                        VARCHAR,
    "DayOfWeek"                         VARCHAR,
    "FlightDate"                        VARCHAR,
    "Reporting_Airline"                 VARCHAR,
    "DOT_ID_Reporting_Airline"          VARCHAR,
    "IATA_CODE_Reporting_Airline"       VARCHAR,
    "Tail_Number"                       VARCHAR,
    "Flight_Number_Reporting_Airline"   VARCHAR,
    "OriginAirportID"                   VARCHAR,
    "OriginAirportSeqID"                VARCHAR,
    "OriginCityMarketID"                VARCHAR,
    "Origin"                            VARCHAR,
    "OriginCityName"                    VARCHAR,
    "OriginState"                       VARCHAR,
    "OriginStateFips"                   VARCHAR,
    "OriginStateName"                   VARCHAR,
    "OriginWac"                         VARCHAR,
    "DestAirportID"                     VARCHAR,
    "DestAirportSeqID"                  VARCHAR,
    "DestCityMarketID"                  VARCHAR,
    "Dest"                              VARCHAR,
    "DestCityName"                      VARCHAR,
    "DestState"                         VARCHAR,
    "DestStateFips"                     VARCHAR,
    "DestStateName"                     VARCHAR,
    "DestWac"                           VARCHAR,
    "CRSDepTime"                        VARCHAR,
    "DepTime"                           VARCHAR,
    "DepDelay"                          VARCHAR,
    "DepDelayMinutes"                   VARCHAR,
    "DepDel15"                          VARCHAR,
    "DepartureDelayGroups"              VARCHAR,
    "DepTimeBlk"                        VARCHAR,
    "TaxiOut"                           VARCHAR,
    "WheelsOff"                         VARCHAR,
    "WheelsOn"                          VARCHAR,
    "TaxiIn"                            VARCHAR,
    "CRSArrTime"                        VARCHAR,
    "ArrTime"                           VARCHAR,
    "ArrDelay"                          VARCHAR,
    "ArrDelayMinutes"                   VARCHAR,
    "ArrDel15"                          VARCHAR,
    "ArrivalDelayGroups"                VARCHAR,
    "ArrTimeBlk"                        VARCHAR,
    "Cancelled"                         VARCHAR,
    "CancellationCode"                  VARCHAR,
    "Diverted"                          VARCHAR,
    "CRSElapsedTime"                    VARCHAR,
    "ActualElapsedTime"                 VARCHAR,
    "AirTime"                           VARCHAR,
    "Flights"                           VARCHAR,
    "Distance"                          VARCHAR,
    "DistanceGroup"                     VARCHAR,
    "CarrierDelay"                      VARCHAR,
    "WeatherDelay"                      VARCHAR,
    "NASDelay"                          VARCHAR,
    "SecurityDelay"                     VARCHAR,
    "LateAircraftDelay"                 VARCHAR,
    "FirstDepTime"                      VARCHAR,
    "TotalAddGTime"                     VARCHAR,
    "LongestAddGTime"                   VARCHAR,
    "DivAirportLandings"                VARCHAR,
    "DivReachedDest"                    VARCHAR,
    "DivActualElapsedTime"              VARCHAR,
    "DivArrDelay"                       VARCHAR,
    "DivDistance"                       VARCHAR,
    "Div1Airport"                       VARCHAR,
    "Div1AirportID"                     VARCHAR,
    "Div1AirportSeqID"                  VARCHAR,
    "Div1WheelsOn"                      VARCHAR,
    "Div1TotalGTime"                    VARCHAR,
    "Div1LongestGTime"                  VARCHAR,
    "Div1WheelsOff"                     VARCHAR,
    "Div1TailNum"                       VARCHAR,
    "Div2Airport"                       VARCHAR,
    "Div2AirportID"                     VARCHAR,
    "Div2AirportSeqID"                  VARCHAR,
    "Div2WheelsOn"                      VARCHAR,
    "Div2TotalGTime"                    VARCHAR,
    "Div2LongestGTime"                  VARCHAR,
    "Div2WheelsOff"                     VARCHAR,
    "Div2TailNum"                       VARCHAR,
    "Div3Airport"                       VARCHAR,
    "Div3AirportID"                     VARCHAR,
    "Div3AirportSeqID"                  VARCHAR,
    "Div3WheelsOn"                      VARCHAR,
    "Div3TotalGTime"                    VARCHAR,
    "Div3LongestGTime"                  VARCHAR,
    "Div3WheelsOff"                     VARCHAR,
    "Div3TailNum"                       VARCHAR,
    "Div4Airport"                       VARCHAR,
    "Div4AirportID"                     VARCHAR,
    "Div4AirportSeqID"                  VARCHAR,
    "Div4WheelsOn"                      VARCHAR,
    "Div4TotalGTime"                    VARCHAR,
    "Div4LongestGTime"                  VARCHAR,
    "Div4WheelsOff"                     VARCHAR,
    "Div4TailNum"                       VARCHAR,
    "Div5Airport"                       VARCHAR,
    "Div5AirportID"                     VARCHAR,
    "Div5AirportSeqID"                  VARCHAR,
    "Div5WheelsOn"                      VARCHAR,
    "Div5TotalGTime"                    VARCHAR,
    "Div5LongestGTime"                  VARCHAR,
    "Div5WheelsOff"                     VARCHAR,
    "Div5TailNum"                       VARCHAR,
    "_TRAILING_EMPTY_COL"               VARCHAR,  -- Captures the trailing comma phantom column 

    -- Metadata columns: audit trail for when/where this row came from. 
    -- These are populated automatically by COPY INTO via METADATA$ functions. 

    "_SOURCE_FILE"                      VARCHAR, 
    "_LOAD_TIMESTAMP"                   TIMESTAMP_NTZ

); 
