USE ROLE ACCOUNTADMIN;
USE DATABASE DOT_FLIGHTS;
USE SCHEMA RAW;
USE WAREHOUSE DOT_FLIGHTS_WH;

CREATE OR REPLACE STAGE S3_DOT_FLIGHTS_STAGE
    STORAGE_INTEGRATION = S3_DOT_FLIGHTS_INT
    URL = '[S3 Bucket]/dot_flights/raw/flights'
    FILE_FORMAT = (
        TYPE = 'CSV' 
        COMPRESSION = 'NONE' 
        FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
        SKIP_HEADER = 1 
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    );

-- Test: list the files Snowflake can see through the stage
LIST @S3_DOT_FLIGHTS_STAGE;
